.PHONY: up
up:
	python3 post.py

.PHONY: test
test:
	python3 test.py

.PHONY: pac
pac:
	sudo apt install python3

.PHONY: open
open:
	python3 test-open-close/open.py

.PHONY: close
close:
	python3 test-open-close/close.py