FROM php:7.4-fpm
COPY php.ini /usr/local/etc/php/

RUN cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer

RUN apt update && apt install -y git zip unzip vim libonig-dev libzip-dev libxml2-dev libgd-dev curl

RUN git clone https://github.com/phpredis/phpredis.git /usr/src/php/ext/redis

# redis mysql
RUN docker-php-ext-install pdo_mysql mbstring zip xml gd redis

# npm
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install -y nodejs
RUN npm install npm@latest -g

# composer install
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# authority
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
# composer pass
ENV PATH $PATH:/composer/vendor/bin
# laravel install
RUN composer global require "laravel/installer"

WORKDIR /var/www/
